[project]
name = "11-agent-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "nest-asyncio>=1.6.0",
    "openai-agents>=0.1.0",
    "python-dotenv>=1.1.1",
]
