[project]
name = "27-external-tracing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langfuse>=3.8.0",
    "openai-agents>=0.4.0",
    "openinference-instrumentation-openai-agents>=1.3.0",
]
